language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get install -yy gcc
  - sudo apt-get install -yy portaudio19-dev
install:
  - pip install poetry
  - poetry install -E "dropbox fitbit fritz fswatcher ftp gmail http-server miflora pushbullet sound"
script:
  - poetry run make lint
  - poetry run make test
after_success:
  - poetry run coveralls
