language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get install -yy gcc
  - sudo apt-get install -yy portaudio19-dev
install:
  - ./.travis/install.sh
script:
  - poetry run make lint
  - poetry run make test
after_success:
  - poetry run coveralls
