language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  # Test faceR on nightly builds only
  - [ ${TRAVIS_EVENT_TYPE} == "cron" ] && pip install -e .[faceR]
script:
  - make lint
  - make test
