# Watches the directory '/tmp' for file changes (create, modify, delete) and prints them out

- name: file_watcher
  pull:
    plugin: pnp.plugins.pull.fs.FileSystemWatcher
    args:
      path: "/tmp"
      ignore_directories: True

  push:
    plugin: pnp.plugins.push.simple.Echo