# Watches the directory '/tmp' for file changes (create, modify, delete) and prints them out

- name: file_watcher
  pull:
    plugin: pnp.plugins.pull.fs.FileSystemWatcher
    args:
      path: "/tmp"
      ignore_directories: True
      events: [created, deleted, modified]
      load_file: False

  push:
    plugin: pnp.plugins.push.simple.Echo