# Watches the directory '/tmp' for file changes (create, modify, delete), loads the file (base64 encoded) and
# prints it out.

- name: file_watcher
  pull:
    plugin: pnp.plugins.pull.fs.FileSystemWatcher
    args:
      path: "/tmp"
      ignore_directories: True

  push:
    plugin: pnp.plugins.push.fs.FileLoad
    args:
      base64: true
    deps:
      plugin: pnp.plugins.push.simple.Echo