udfs:
  - name: my_str  # Register the builtin str callable as my_str
    plugin: str
  - name: my_on_off  # Register a custom callable
    plugin: pnp.utils.on_off
  - name: count  # Instantiate a Counter user defined function
    plugin: pnp.plugins.udf.simple.Counter
    args:  # The presence of args tells pnp to instantiate a Counter - important because it has a state (the actual count)
      init: 1
  - name: count0
    plugin: pnp.plugins.udf.simple.Counter
    args:  # Even without an argument (init is 0 by default), the args is important: This tells pnp to instantiate a Counter. Otherwise it is assumed to be a callable
  - name: count_err
    plugin: pnp.plugins.udf.simple.Counter  # Without args. Each time you call count_err this will actually call the __init__ of the Counter class
tasks:
  - name: hello-world
    pull:
      plugin: pnp.plugins.pull.simple.Repeat
      args:
        wait: 1
        repeat: "Hello World"
    push:
      - plugin: pnp.plugins.push.simple.Echo
        selector:
          on_off: "lambda d: my_on_off(True)"
          str: "lambda d: my_str(d)"
          cnt0: "lambda d: count0()"
          cnt1: "lambda d: count()"
          cnterr: "lambda d: count_err(name='error')"  # This will actually create a counter class instead of counting
          data: "lambda d: d"
