---
- name: dropbox_sync_notify
  pull:
    plugin: pnp.plugins.pull.fs.FileSystemWatcher
    args:
      path: "/tmp"
      ignore_directories: true
      events:
        - created
        - modified
      load_file: false
  push:
    - plugin: pnp.plugins.push.storage.Dropbox
      args:
        api_key: "{{env::DROPBOX_API_KEY}}"
      selector:
        data: "lambda data: data.source"  # Absolute path to file
        target_file_name: "lambda data: basename(data.source)"  # File name only
      deps:
        - plugin: pnp.plugins.push.notify.Pushbullet
          args:
            api_key: "{{env::PUSHBULLET_API_KEY}}"
          selector: data.raw_link
