---
# You can define multiple pushes to push the pulled data to multiple sinks.
# This example yields the string 'Hello World' every second. Both pushes print it out.

- name: multipush
  pull:
    plugin: pnp.plugins.pull.simple.Repeat
    args:
      interval: 1s
      repeat: "Hello World"
  push:
    - plugin: pnp.plugins.push.simple.Echo
    - plugin: pnp.plugins.push.simple.Echo
