---
# Define selectors to parse / tailor your pulled data. Each selector is bound to a push that controls which input
# is ingested.

# This example yields the string 'Hello World' every second. The first push gets 'Hello' and prints it out.
# The second one gets 'World' and prints it out.

- name: selector
  pull:
    plugin: pnp.plugins.pull.simple.Repeat
    args:
      wait: 1
      repeat: "Hello World"
  push:
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.split(' ')[0]"
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.split(' ')[1]"
