# By returning a pre-defined constant (SUPRESSME, SUPPRESS, SUPPRESS_ME) from a selector you can suppress
# the execution of a push.

# This example counts from 0 to infinity. The push is only fired when the counter is even.

- name: suppress
  pull:
    plugin: pnp.plugins.pull.simple.Count
    args:
      wait: 1
  push:
    - plugin: pnp.plugins.push.simple.Echo
      # variable suppress is basically a constant that tells the push not to execute
      # So the echo push is only executed when the counter is even
      selector: "payload if int(payload) % 2 == 0 else SUPPRESSME"