---
# As a matter of fact dependencies can have dependencies as well ;-)

# This example yields the string 'Hello World' every second. The first push gets 'Hello' and just returns it.
# The second one gets 'World' and just returns it. The child's extract the first three ('Hel' / 'Wor') resp.
# the remaining two ('lo' / 'ld') characters from both inputs and print them out.

- name: complex
  pull:
    plugin: pnp.plugins.pull.simple.Repeat
    args:
      wait: 1
      repeat: "Hello World"
  push:
    - plugin: pnp.plugins.push.simple.Nop
      selector: "payload.split(' ')[0]"
      deps:
        - plugin: pnp.plugins.push.simple.Echo
          selector: "payload[:3]"
        - plugin: pnp.plugins.push.simple.Echo
          selector: "payload[3:]"
    - plugin: pnp.plugins.push.simple.Nop
      selector: "payload.split(' ')[1]"
      deps:
        - plugin: pnp.plugins.push.simple.Echo
          selector: "payload[:3]"
        - plugin: pnp.plugins.push.simple.Echo
          selector: "payload[3:]"
