# DHT temperature and humidity polling (requires extra 'dht')
- name: dht
  pull:
    plugin: pnp.plugins.pull.sensor.DHT
    args:
      device: dht22
      data_gpio: 18
      interval: 5s
  push:
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.humidity"
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.temperature"
