# You can have one pull and multiple pushes
- name: simple
  pull:
    plugin: pnp.plugins.pull.simple.Count
    args:
      wait: 1
  push:
    - plugin: pnp.plugins.push.simple.Echo
    - plugin: pnp.plugins.push.simple.Echo
