# Parse the payload via a so called selector
- name: "simple"
  pull:
    plugin: pnp.plugins.pull.simple.Repeat
    args:
      wait: 1
      repeat: "Hello World"
  push:
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.split(' ')[0]"
    - plugin: pnp.plugins.push.simple.Echo
      selector: "payload.split(' ')[1]"