# Publishes a counter to the mqtt topic 'test/counter'
# The other task subscribes to the topic and prints out the counter.
# Is it basically our simple example with a mqtt broker in between.
# Since version 0.7.0 the MQTTPull plugin will emit an enveloped payload.
# To restore the behaviour previous to 0.7.0 just uncomment the selector.

- name: publisher
  pull:
    plugin: pnp.plugins.pull.simple.Count
    args:
      wait: 1

  push:
    plugin: pnp.plugins.push.mqtt.MQTTPush
    args:
      host: localhost
      topic: test/counter

- name: subscriber
  pull:
    plugin: pnp.plugins.pull.mqtt.MQTTPull
    args:
      host: localhost
      topic: test/counter
  push:
    plugin: pnp.plugins.push.simple.Echo
    # selector: "{'data': data}"