# DHT temperature and humidity polling (requires extra 'dht')
# Pull returns a dictionary containing the temperature and humidity.

- name: rest
  pull:
    plugin: pnp.plugins.pull.rest.RestServer
    args:
      port: 5000
      allowed_methods: [GET, POST]
  push:
    - plugin: pnp.plugins.push.simple.Echo
      selector: '{"topic": "/".join(data.levels[:-1]), "data": data.levels[-1]}'
#    - plugin: pnp.plugins.push.mqtt.MQTTPush
#      selector: '{"topic": "/".join(data.levels[:-1]), "data": data.levels[-1]}'
#      args:
#        host: localhost
