# Starts up an http server on port 5000 and listens on "any" endpoint
# Push will print the actual calling on the screen

- name: rest
  pull:
    plugin: pnp.plugins.pull.http.Server
    args:
      port: 5000
      allowed_methods: [GET, POST]
  push:
    - plugin: pnp.plugins.push.simple.Echo
