- name: zway_receiver
  pull:
    plugin: pnp.plugins.pull.zway.ZwayReceiver
    args:
      port: 5000
      device_mapping:
        vdevice1: dev1
        vdevice2: dev2
        vdevice3: dev3
      url_format: "%DEVICE%?value=%VALUE%"
      ignore_unknown_devices: True
  push:
    - plugin: pnp.plugins.push.simple.Echo