#!/bin/bash

PACKAGE=$(dirname `which $0`)

# Import helper
. ${PACKAGE}/util

function help {
    if [ ! -z "$1" ]; then
        echo "$1"
    fi
    echo "Usage: $0 pyVersion"
    echo "- pyVersion: Python version to ramp up (e.g. 3.5, 3.6, ...)"
}

function run() {
    VERSION=$1
    echo "Running version: ${VERSION}"

    SOURCE=`abspath "${PACKAGE}/.."`

    distro=buster

#    if [ ${VERSION} == "3.8" -o ${VERSION} == "3.9" ]; then
#        distro=buster
#    fi

    echo "Ubuntu Distribution is: ${distro}"

    docker run -it --rm \
        -v ${SOURCE}:/src \
        python:${VERSION}-${distro} \
        bash -c "cd /src; pip install poetry && poetry install -E 'dropbox fitbit fswatcher ftp gmail miflora pushbullet speedtest' && bash"
}

PYVERSION=$1

if [ -z "$PYVERSION" ]; then
    help "Please specify the python version"
    exit 1
fi

run ${PYVERSION}
