# Uses the dictmentor package to augment the configuration
# by dictmentor extensions.
# Make sure to export the environment variable to echo:
# export MESSAGE="Hello World"

tasks:
  - name: dictmentor
    pull:
      external: repeat.pull
    push:
      - external: echo.push
      - external: nop.push
